### ISSUE TITLE
Build Frontend

### ISSUE THREAD

**Issue by KhaledAjaj2026** [KhaledAjaj2026/mhw-notebook-overhaul#2]
Instead of revamping old website, use this opportunity to build entire new website. Use React this time to cut development time and make compartmentalization easier. Use styled components and similar libraries for styling JSX. 

## Goal:

Build entire frontend using React according to Figma design.

## Tasks:

- [ ] Build components that neatly present API data.
- [ ] Use Axios for API calls.
- [ ] Use pre-styled components libraries for quick styling.
