### ISSUE TITLE
Implement Interactivity & New Features

### ISSUE THREAD

**Issue by KhaledAjaj2026** [KhaledAjaj2026/mhw-notebook-overhaul#4]
Implement interactive elements into website, such as search behavior and scroll animations. Research features that websites can have for a better user experience. Implement these features that promote longer user sessions and a greater impact of website's contents. 

## Goal:

Program Interactive features into website, design new features for user experience.

## Tasks:

- [ ] Make search bar retrieve data from API, use Axios for API calls.
- [ ] Animate loading sequence
- [ ] Create original cursor sprite akin to scout-flies
- [ ] Generate loading screen for page routing
- [ ] Query of previous/ next searches (back/fwd)
- [ ] Unique themes for each monster's habitat (AF, CH, etc.)
