### ISSUE TITLE
Testing via Jest & Cypress

### ISSUE THREAD

**Issue by KhaledAjaj2026** [KhaledAjaj2026/mhw-notebook-overhaul#5]
Begin implementing tests into workflow, create habit of ensuring software works as intended before deployment. Use Jest for testing JavaScript codebase. Implement tests for unit and functional checks. Use Cypress for Integration checks.

## Goal:

Ensure logic works according to unit, functional, and integration test cases.

## Tasks:

- [ ] Create Unit tests
- [ ] Create Functional tests
- [ ] Create Integration tests
- [ ] Maintain habit for testing new features
