### ISSUE TITLE
Logic Optimization

### ISSUE THREAD

**Issue by KhaledAjaj2026** [KhaledAjaj2026/mhw-notebook-overhaul#6]
While the website works as intended, one could describe its codebase as a "brute-force" approach to problems: gets the job done but not in the best way. Parse through codebase to refactor functions and to invoke best-practices in programming. Refactor code into separate files for separation of logic and better readability.

## Goal:

Refactor all JavaScript logic. Optimize current code and implement best practices.

## Tasks:

- [ ] Delete autocomplete code, remake via ES6+ features
- [ ] Separate logic into different files
- [ ] Research more optimal method for serving high-quality images
- [ ] Change responsive behavior from "onload"
