### ISSUE TITLE
Accessibility Functionality

### ISSUE THREAD

**Issue by KhaledAjaj2026** [KhaledAjaj2026/mhw-notebook-overhaul#8]
Ensure entire website is navigable when using only keyboard. Set order of tab-able items in convenient order for keyboard users. Ensure all website content is easily parseable by screen-readers, and that content is read and emphasized in correct order an manner. Implement 3rd-party accessibility widget on the side for user convenience.

## Goal:

Make site completely accessible to keyboard navigators, as well as screen-readers.

## Tasks:

- [ ] Make site keyboard-friendly
- [ ] Make site screen-reader-friendly
- [ ] Implement 3rd-party accessibility widget
